### ISSUE TITLE
alias gc='git commit -m'  sounds crazy

### ISSUE THREAD

**Issue by zhuangya** [barryclark/bashstrap#1]
hey @barryclark, thanks for your bashstrap. :)

but i don't think `alias gc='git commit -m' ` is a good idea since there are [a](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) [lot](http://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message) [of](https://www.google.co.jp/search?q=how+to+write+git+commit+message&oq=how+to+write+git+commit+message&aqs=chrome..69i57j0.5196j0j1&sourceid=chrome&espv=210&es_sm=119&ie=UTF-8) articles writing how to write a **good** git commit message.

**Comment by barryclark** [comment]
Thanks, @zhuangya!

That shortcut probably caters to my preference quite a bit more than others. You could certainly change that for your own preferences after cloning :) A lot of those aliases really are more suggestions that good practices/standards.

Thanks!
